use curso
--CRIANDO TABELA
--DROP TABLE SALDOS
--DROP FUNCTION SALDO
CREATE TABLE SALDOS
 (NUM_CONTA  VARCHAR(10) NOT NULL PRIMARY KEY,
  SALDO_INICIAL DECIMAL(10,2),
  SALDO_FINAL   DECIMAL(10,2)
  );
--INSERINDO VALORES
  INSERT INTO SALDOS VALUES ('123-9',1000,1000),('124-7',1000,500),('125-6',500,1000);


--FUNÇAO ESCALAR
CREATE FUNCTION SALDO(@CONTA VARCHAR(10)) 
	returns DECIMAL 
	AS   
   
BEGIN       
	DECLARE @SALDO DECIMAL;       
	SELECT @SALDO = SALDO_FINAL-SALDO_INICIAL      
		FROM SALDOS
		WHERE NUM_CONTA=@CONTA; 
		      
	IF ( @SALDO IS NULL )         
	SET @SALDO = 0;       
	RETURN @SALDO;   
END;
	
--invocante a funcao SALDO
	SELECT NUM_CONTA,
	       SALDO_INICIAL,
		   SALDO_FINAL,
		   DBO.SALDO(NUM_CONTA) AS SALDO
		   FROM   SALDOS
		   
 
